---
# Per environment values which override defaults in court-case-test-app/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: court-case-test-app-dev.hmpps.service.justice.gov.uk
    cert_secret: court-probation-dev-cert-secret

  env:
    INGRESS_URL: "https://court-case-test-app-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

